[package]
name = "rclip"
version = "0.0.1"
edition = "2021"
authors=["Drew Chase"]
categories= ["cli", "parser"]
license="GNU-3.0"
repository="https://github.com/drew-chase/rclip"
readme="readme.md"
documentation="https://docs.rs/rclip"

[dependencies]
